# Generated by Django 4.0.3 on 2022-03-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_newsitem_media_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-value']},
        ),
        migrations.AlterField(
            model_name='stock',
            name='misc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
