# Generated by Django 4.0.2 on 2022-03-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_portfolio_options_alter_stock_misc'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
