# Generated by Django 4.0.2 on 2022-03-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('0', 'sell'), ('1', 'buy')], max_length=1, null=True),
        ),
    ]
