# Generated by Django 4.0.2 on 2022-03-06 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_transaction_portfolio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='portfolio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.portfolio'),
        ),
    ]
