# Generated by Django 4.0.2 on 2022-03-06 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stock_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.stock'),
        ),
    ]
