# Generated by Django 4.0.2 on 2022-03-06 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_transaction_portfolio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='portfolio_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_id', to='users.portfolio'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stock_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_id', to='users.stock'),
        ),
    ]
