# Generated by Django 4.0.2 on 2022-03-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_stock_slug'),
        ('users', '0021_remove_newsitem_related_stocks_and_more'),
    ]

    operations = [
    ]
