# Generated by Django 4.0.3 on 2022-03-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_transaction_options_portfolio_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stop_limit',
            field=models.IntegerField(null=True),
        ),
    ]
