# Generated by Django 4.0.3 on 2022-03-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_transaction_portfolio_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stop_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
