# Generated by Django 4.0.3 on 2022-03-27 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_transaction_stop_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='money',
            new_name='actual_money',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='visible_money',
            field=models.FloatField(default=5000),
        ),
        migrations.AddField(
            model_name='stock',
            name='ask_price',
            field=models.FloatField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='bid_price',
            field=models.FloatField(default=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Open_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(max_length=1)),
                ('stop_limit', models.IntegerField(blank=True, null=True)),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_portfolio_id', to='users.portfolio')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_stock_id', to='users.stock')),
            ],
            options={
                'ordering': ['-status', '-stock_id', '-price'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Closed_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(max_length=1)),
                ('stop_limit', models.IntegerField(blank=True, null=True)),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_portfolio_id', to='users.portfolio')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_stock_id', to='users.stock')),
            ],
            options={
                'ordering': ['-status', '-stock_id', '-price'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='holding',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.closed_transaction'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
