# Generated by Django 4.0.3 on 2022-03-29 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_closedtransaction_opentransaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='transaction',
        ),
    ]
