# Generated by Django 4.0.3 on 2022-03-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_holding_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='fourth_last_traded_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='second_last_traded_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='third_last_traded_price',
        ),
    ]
