# Generated by Django 4.0.3 on 2022-04-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_closedtransaction_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='inital_money',
            new_name='initial_money',
        ),
    ]
