# Generated by Django 4.0.3 on 2022-04-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_portfolio_watchlist_stock_second_last_traded_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='misc',
        ),
    ]
