# Generated by Django 4.0.3 on 2022-04-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_remove_stock_misc'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_logo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
