# Generated by Django 4.0.3 on 2022-04-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_stock_stock_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='initial_money',
            field=models.FloatField(default=100000),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='visible_money',
            field=models.FloatField(default=100000),
        ),
    ]
